name = "OrbiJul"
uuid = "efb88e26-0a6c-4577-8477-c29bb6a880cb"
authors = ["Marek Becvar"]
version = "0.1.0"

[deps]
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"

[compat]
Aqua = "0.8"
GLMakie = "0.13.8"
Test = "1.9"
julia = "1.10"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]
